### ISSUE TITLE
Example fails: Unable to load asset: assets/ipadic/char.bin

### ISSUE THREAD

**Issue by suztomo** [dttvn0010/mecab_dart#1]
@dttvn0010 I tried the example in https://pub.dev/packages/mecab_dart#-example-tab-,  but I got the following exception. Am I or the library missing something?

```
Debug service listening on ws://127.0.0.1:63103/mbLZIt2SCig=/ws
Syncing files to device iPhone 11 Pro Max...
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: assets/ipadic/char.bin
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      Mecab.copyFile (package:mecab_dart/mecab_dart.dart:52:36)
#2      Mecab.init (package:mecab_dart/mecab_dart.dart:71:11)
<asynchronous suspension>
#3      _MyAppState.initPlatformState (package:hello_mecab_dart/main.dart:33:20)
<asynchronous suspension>
#4      _MyAppState.initState (package:hello_mecab_dart/main.dart:22:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
#10     RenderObjectToWidgetElement.<…>
```

<img width="1261" alt="Screen Shot 2020-04-01 at 12 44 40 PM" src="https://user-images.githubusercontent.com/28604/78163564-910ef300-7416-11ea-9602-c8c9405c498d.png">

**Comment by dttvn0010** [comment]
Have you configure the assets folder in pubspec.yaml:

**Comment by dttvn0010** [comment]
And also make sure to create the "assets" folder (at the same level with ios/android/lib) and then copy the dictionary folder from : https://github.com/dttvn0010/mecab_dart/tree/master/example/assets/ipadic to the "assets" folder

**Comment by suztomo** [comment]
It works. Thank you.
